"""add recipe tag association

Revision ID: 09c96b3fcd53
Revises: 41feef846672
Create Date: 2022-07-20 12:18:01.667107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c96b3fcd53'
down_revision = '41feef846672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_tags',
    sa.Column('recipe_pk', sa.Integer(), nullable=False),
    sa.Column('tag_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_pk'], ['recipes.pk'], ),
    sa.ForeignKeyConstraint(['tag_pk'], ['tags.pk'], ),
    sa.PrimaryKeyConstraint('recipe_pk', 'tag_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_tags')
    # ### end Alembic commands ###
