"""add ingredients to recipes

Revision ID: 46c4ff832885
Revises: 09c96b3fcd53
Create Date: 2022-07-20 14:54:09.995728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c4ff832885'
down_revision = '09c96b3fcd53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_in_recipe',
    sa.Column('recipe_pk', sa.Integer(), nullable=False),
    sa.Column('ingredient_pk', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_pk'], ['ingredients.pk'], ),
    sa.ForeignKeyConstraint(['recipe_pk'], ['recipes.pk'], ),
    sa.PrimaryKeyConstraint('recipe_pk', 'ingredient_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients_in_recipe')
    # ### end Alembic commands ###
