"""add slug field to tag

Revision ID: a062940b5702
Revises: 46c4ff832885
Create Date: 2022-07-21 13:18:18.155216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a062940b5702'
down_revision = '46c4ff832885'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('slug', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'slug')
    # ### end Alembic commands ###
