version: '3.8'

services:
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres-foodgram
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
